### ISSUE TITLE
update favicon

### ISSUE THREAD

**Issue by marlon-wiprud** [TuringAdvisoryGroup/uniswap-frontend#1]

**Comment by brevityy** [comment]
@marlon-wiprud do you have specs here or do you need them from @rachel-tryroll?

**Comment by rachel-tryroll** [comment]
Can you guys please post screenshots before closing design related tickets?

**Comment by marlon-wiprud** [comment]
I used the same favicon file used on app.tryroll.com

- @rachel-tryroll  will do
