### ISSUE TITLE
Change the source/order of images of tokens

### ISSUE THREAD

**Issue by sidko** [TuringAdvisoryGroup/uniswap-frontend#13]
Let's change the way in which we look for images. The following are the places to find image sources, in the order of priority: 
1. Default Uniswap image source (trust wallet github repo)
2. Internal images of tokens stored in our code (specific to Roll)
3. Default generic token image

For example, when looking for what image to use for HUE, you first want to look at the default trust wallet location. HUE image will be found there already, so no need to go to the location that we use internally for the HUE image on S3.

**Comment by marlon-wiprud** [comment]
All tokens default to trust wallet for images unless explicitly stated otherwise.
