### ISSUE TITLE
Failing circleci job

### ISSUE THREAD

**Issue by marlon-wiprud** [TuringAdvisoryGroup/uniswap-frontend#18]
**Bug Description**
Unable to successfully run push-to-ecr job on develop branch

**Steps to Reproduce**
push new commit to develop branch

**Expected Behavior**
both push-to-ecr and test jobs run successfully on circle ci

**Additional Context**
Here is a link to the failed circleCI job: https://circleci.com/gh/TuringAdvisoryGroup/uniswap-frontend/94?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

@algogrit any thoughts?

**Comment by algogrit** [comment]
Its failing while building the image...

```
Step 7/18 : RUN npm install -g yarn
 ---> Running in ccacdf95b023
npm ERR! code EEXIST
npm ERR! syscall symlink
npm ERR! path ../lib/node_modules/yarn/bin/yarn.js
npm ERR! dest /usr/local/bin/yarn
npm ERR! errno -17
npm ERR! EEXIST: file already exists, symlink '../lib/node_modules/yarn/bin/yarn.js' -> '/usr/local/bin/yarn'
npm ERR! File exists: /usr/local/bin/yarn
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-01-10T07_11_45_051Z-debug.log
The command '/bin/sh -c npm install -g yarn' returned a non-zero code: 239

Exited with code exit status 239
```

**Comment by algogrit** [comment]
Commenting and trying again: https://github.com/TuringAdvisoryGroup/uniswap-frontend/commit/087d009f00464495c7a04f292e87d72abcf9b8de

CI: https://circleci.com/workflow-run/e55af3da-9bcd-446a-8866-ec50eb4522f0

**Comment by algogrit** [comment]
It's fixed now.
