### ISSUE TITLE
Add JULIEN to our exchange

### ISSUE THREAD

**Issue by sidko** [TuringAdvisoryGroup/uniswap-frontend#27]
**Please provide the following information for your token.**

Token Address: 0xe6710e0cda178f3d921f456902707b0d4c4a332b
Token Name (from contract): Julien
Token Decimals (from contract): 4
Token Symbol (from contract): JULIEN
Uniswap Exchange Address of Token: 0x4cE8d670c0CCEa741829551B347e2eBabdba638F

Image: 

![JULIAN256px](https://user-images.githubusercontent.com/2774509/72284859-f4576900-360f-11ea-9240-67d3f8aa8714.png)

CC @brevityy

**Comment by brevityy** [comment]
Have this issue up #26 but @marlon-wiprud let's use this image.
