### ISSUE TITLE
Add aDAI to frontend under "Tokens" 

### ISSUE THREAD

**Issue by brevityy** [TuringAdvisoryGroup/uniswap-frontend#33]
@marlon-wiprud hold off on this for now, checking with the team to see if they have an image in the github repo. If not, I'll add below.  

**Please provide the following information for your token.**

Token Address: 0xfc1e690f61efd961294b3e1ce3313fbd8aa4f85d
Token Name (from contract): Aave Interest bearing DAI
Token Decimals (from contract): 18
Token Symbol (from contract): aDAI
Uniswap Exchange Address of Token: 0x7cfab87AaC0899c093235b342AC0e5B1ACF159EB
Category: Tokens 
Image in Trust Wallet repo (Y/N)?
If no, please attach image

**Comment by sidko** [comment]
No image on Uniswap

**Comment by brevityy** [comment]
ok, there's no rush here. Let's wait until they get back to us/get an image up

**Comment by brevityy** [comment]
No longer blocked on this. Here is the image in 256x256 from @rachel-tryroll .
 
![aDAI256px](https://user-images.githubusercontent.com/24559073/73027994-92aeb000-3e02-11ea-9aa6-43b0eefda03c.png)

**Comment by sidko** [comment]
In production
