### ISSUE TITLE
Getting an error trying to access the site without web3 wallet connected

### ISSUE THREAD

**Issue by sidko** [TuringAdvisoryGroup/uniswap-frontend#36]
**Bug Description**
Don't force users to connect a web3 wallet when they visit the site. This step should come after they hit 'connect' on the top right. 

**Steps to Reproduce**
Go to https://exchange.tryroll.com in an in private browsing mode and compare to https://uniswap.exchange

**Expected Behavior**
Show the site just as uniswap does

**Additional Context**
<img width="1102" alt="Screen Shot 2020-01-29 at 3 57 35 PM" src="https://user-images.githubusercontent.com/2774509/73396906-5b337e00-42b0-11ea-8017-7dc280d9bb27.png">

**Comment by marlon-wiprud** [comment]
Resolved by modifying an env variable definition
