### ISSUE TITLE
Clicked state of "Roll – Social Money" text in top left corner has a neon blue underline 

### ISSUE THREAD

**Issue by brevityy** [TuringAdvisoryGroup/uniswap-frontend#4]
When the `Roll - Social Money` text is clicked and you revisit the page. The clicked state has a neon blue underline. 

Is the underline here absolutely necessary? If so, can we please change to a less conspicuous color?

<img width="189" alt="Screen Shot 2019-12-16 at 6 52 58 PM" src="https://user-images.githubusercontent.com/24559073/70952778-5171f600-2035-11ea-9f00-4810ba996d61.png">
Zoomed in

<img width="570" alt="Screen Shot 2019-12-16 at 6 49 37 PM" src="https://user-images.githubusercontent.com/24559073/70952666-eaecd800-2034-11ea-888f-bc68ce654b78.png">

**Comment by marlon-wiprud** [comment]
<img width="169" alt="Screen Shot 2019-12-17 at 10 22 14 AM" src="https://user-images.githubusercontent.com/37754165/71008756-2334fa80-20b7-11ea-94d2-08fa67663440.png">


updated the color
