### ISSUE TITLE
Add RCLE to 'Friends of Roll'

### ISSUE THREAD

**Issue by sidko** [TuringAdvisoryGroup/uniswap-frontend#47]
**Please provide the following information for your token.**

Token Address: 0x5a844590c5b8f40ae56190771d06c60b9ab1da1c
Token Name (from contract): Ross Campbell Legal Engineering
Token Decimals (from contract): 18
Token Symbol (from contract): RCLE
Uniswap Exchange Address of Token: 0xd994b83F2Fca809704D6819935D89f3d0f5DE555
Category: Friends of Roll
Image in Trust Wallet repo (Y/N)? Y
If no, please attach image

**Comment by marlon-wiprud** [comment]
Released to production

**Comment by sidko** [comment]
Don't see this yet
<img width="703" alt="Screen Shot 2020-02-06 at 4 23 20 PM" src="https://user-images.githubusercontent.com/2774509/73980053-6f552c00-48fd-11ea-8682-b24cd8e16c56.png">

**Comment by marlon-wiprud** [comment]
<img width="1285" alt="Screen Shot 2020-02-06 at 4 59 39 PM" src="https://user-images.githubusercontent.com/37754165/73982381-1cca3e80-4902-11ea-8f31-8bba0ebf043c.png">

This is what I see on my side on chrome and firefox

**Comment by sidko** [comment]
Ok, shows up now, may just have been a delay during deployment.
