### ISSUE TITLE
Add PAUL

### ISSUE THREAD

**Issue by sidko** [TuringAdvisoryGroup/uniswap-frontend#49]
**Please provide the following information for your token.**

Token Address: 0x8db6Da2120b346FAa7f206841f2FB005BBE0DFD8
Token Name (from contract): Paul
Token Decimals (from contract): 4
Token Symbol (from contract): PAUL
Uniswap Exchange Address of Token: 0xf5498595586b0A83223eA3a369b88E11B9cc1F13 
Category: Social Money
Image in Trust Wallet repo (Y/N)? Y
If no, please attach image

**Comment by marlon-wiprud** [comment]
Released into production
