### ISSUE TITLE
Add SCOTT

### ISSUE THREAD

**Issue by sidko** [TuringAdvisoryGroup/uniswap-frontend#50]
**Please provide the following information for your token.**

Token Address: 0x27fD686Db10E0aE047fe8FE1DE9830C0e0dC3CFA
Token Name (from contract): Scott
Token Decimals (from contract): 4
Token Symbol (from contract): SCOTT
Uniswap Exchange Address of Token: 0x76F455C38AB1FeF84cF27F51065eE1374Fa400e5
Category: Social Money
Image in Trust Wallet repo (Y/N)? Y
If no, please attach image

**Comment by marlon-wiprud** [comment]
Released into production
