### ISSUE TITLE
RDR

### ISSUE THREAD

**Issue by sidko** [TuringAdvisoryGroup/uniswap-frontend#53]
**Please provide the following information for your token.**

Token Address: 0x3C9Ca73d5309d38c6F2C21b78b9aE1f4b2441188
Token Name (from contract): RADAR
Token Decimals (from contract): 4
Token Symbol (from contract): RDR
Uniswap Exchange Address of Token: 0x0385619bbeAED92aC451806a7ab79905973cE806
Category: Social Money
Image in Trust Wallet repo (Y/N)? Y
If no, please attach image

**Comment by marlon-wiprud** [comment]
Released to production
