### ISSUE TITLE
Add JAMM to the Exchange

### ISSUE THREAD

**Issue by brevityy** [TuringAdvisoryGroup/uniswap-frontend#80]
**Please provide the following information for your token.**

Token Address: 0x56687cf29Ac9751Ce2a4E764680B6aD7E668942e
Token Name (from contract): FlynnJamm
Token Decimals (from contract): 4
Token Symbol (from contract): JAMM
Uniswap Exchange Address of Token: 0xFea2eB40C51B73da5C79E81D7E896b0b90DcA3Ad
Category: Social Money
Image in Trust Wallet repo (Y/N)? Y
If no, please attach image

**Comment by sidko** [comment]
Check the email thread - this has been completed
